### ISSUE TITLE
Potential Improvement: Resetting session variables after restarting the server 

### ISSUE THREAD

**Issue by mansimov** [founderhacker/unidentified_feedback#11]
I noticed that the session variables (in particular `session[:tweet_url]`) stay after restarting the server with `bin/dev`. You can see this by the paragraph `Tweet sent!` appearing on the web page after sending a tweet and restarting the server.

We may want to reset the session variables, especially if there is a certain feature we want to test with them.

I tried resetting them in different ways but didn't get anywhere. Suggestions on how to address this issue?

**Comment by ryanckulp** [comment]
yo! great question.

you can reset a session after* it's used (e.g. in a view) via `session[:key_name] = nil`.

**Comment by mansimov** [comment]
Thanks!
