### ISSUE TITLE
Feature request -- threading support

### ISSUE THREAD

**Issue by ryanckulp** [founderhacker/unidentified_feedback#5]
If multiple visitors submit feedback to the same organization or person on Twitter, it could be nice to consolidate all that feedback into a single Twitter thread.

Hints:

* in an ActiveRecord callback for Feedback db inserts, OR during the `TwitterService` invocation, figure out if the Tweet is being directed to an existing Feedback record's `recipient_handle`. if so, modify the TwitterService `message` to attach the Tweet as a thread item

Bounty: $200

**Comment by mansimov** [comment]
Addressed in this pull request https://github.com/founderhacker/unidentified_feedback/pull/8
